# Workshop Redes Neurais
## Grupo Turing

### Básicos de Pytorch

Primeiro vamos ver alguns análogos entre **numpy** e **Pytorch**

#### Matrizes
 - Em Pytorch, matrizes (*arrays*) são chamados de tensores.
 - Uma matriz $3\times3$, por exemplo é um tensor $3\times3$
 - Podemos criar um array numpy com o método `np.numpy()`
 - Podemos pegar o tipo do array com `type()`
 - Podemos pegar o formato do *array* com `np.shape()`. Linha $\times$ Coluna

In [1]:
import numpy as np

array = [[1,2,3],[4,5,6]]
primeiro_array = np.array(array) # array 2x3
print(f"Array do tipo: {type(primeiro_array)}")
print(f"Array de formato: {np.shape(primeiro_array)}")
print(primeiro_array)

Array do tipo: <class 'numpy.ndarray'>
Array de formato: (2, 3)
[[1 2 3]
 [4 5 6]]


- Criamos um tensor com o método `torch.tensor()`
- `tensor.type`: tipo do *array*, nesse caso um tensor
- `tensor.shape`: formato do *array*. Linha $\times$ Coluna 

In [2]:
import torch

tensor = torch.Tensor(array)
print(f"Array do tipo: {tensor.type}")
print(f"Array de formato: {tensor.shape}")
print(tensor)

Array do tipo: <built-in method type of Tensor object at 0x7f1fb719f280>
Array de formato: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


Podemos fazer a alocação de *arrays* de maneira análoga nas duas linguages:
 - `np.ones()` = `torch.ones()`
 - `np.random.rand()` = `torch.rand()`

In [4]:
print(f"Numpy:\n {np.ones((2,3))}\n")

print(torch.ones((2,3)))

Numpy:
 [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
print(f"Numpy:\n {np.random.rand(2,3)}\n")

print(torch.rand(2,3))

Numpy:
 [[0.56135678 0.05051988 0.07082774]
 [0.59575574 0.28259038 0.09951857]]

tensor([[0.5189, 0.9531, 0.6901],
        [0.6453, 0.1515, 0.2072]])


Em muitos pontos **numpy** e **pytorch** são bem parecidos em suas estruturas, e muitas das vezes podemos utilizar os dois em conjunto. Assim normalmente convertemos resultados de redes neurais - que são tensores - para **arrays** de **numpy**.

Os métodos para fazer a conversão entre tensores e arrays numpy:
 - `torch.from_numpy()`: de um array numpy para um tensore
 - `numpy()`: de um tensor para um array numpy

In [9]:
array = np.random.rand(2,2)
print(f"{type(array)} \n {array} \n")

de_numpy_para_tensor = torch.from_numpy(array)
print(f"{de_numpy_para_tensor} \n")

tensor = de_numpy_para_tensor
de_tensor_para_numpy = tensor.numpy()
print(f"{type(de_tensor_para_numpy)} \n {de_tensor_para_numpy}")

<class 'numpy.ndarray'> 
 [[0.65743502 0.85140118]
 [0.22173859 0.32159757]] 

tensor([[0.6574, 0.8514],
        [0.2217, 0.3216]], dtype=torch.float64) 

<class 'numpy.ndarray'> 
 [[0.65743502 0.85140118]
 [0.22173859 0.32159757]]


### Matemática básica com Pytorch
*considere a e b dois tensores*

- Redefinir o tamanho: `view()`
- Adição: `torch.add(a,b)` = a + b
- Subtração: `a.sub(b)` = a - b
- Multiplicação elemento-a-elemento = `torch.mul(a,b)` = a * b
- Divisão elemento-a-elemento = torch.div(a,b) = a / b
- Média: a.mean()
- Desvio Padrão (Standart Deviantion - std): a.std()

In [16]:
tensor = torch.ones(3,3)
print("\n", tensor, "\n")

print(f"{tensor.view(9).shape}: {tensor.view(9)} \n")

print(f"Adição: \n{torch.add(tensor, tensor)} \n")

print(f"Subtração: \n{torch.sub(tensor, tensor)} \n")

print(f"Multiplicação elemento-a-elemento: \n{torch.mul(tensor, tensor)} \n")

print(f"Divisão elemento-a-elemento: \n{torch.div(tensor, tensor)} \n")

tensor = torch.Tensor([1,2,3,4,5])
print(f"Média: {tensor.mean()} \n")

print(f"Desvio padrão: {tensor.std()} \n")


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

torch.Size([9]): tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]) 

Adição: 
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) 

Subtração: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

Multiplicação elemento-a-elemento: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Divisão elemento-a-elemento: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Média: 3.0 

Desvio padrão: 1.5811388492584229 



# ATENÇÃO COLOCAR/FAZER EXPLICAÇÃO DE BACKPROP AQUI

### Variáveis

- Acumulam os gradientes
- Na rede neural utilizaremos pytorch. Como explicamos nas redes neurais os gradientes são calculados na *backpropagation*.
- A diferença entre variáveis e tensores é a de que variáveis acumulam os gradientes
- Também podemos fazer operações matemáticas com variáveis
- Dessa maneira, se queremos fazer a *backpropagation* precisamos de variáveis

In [18]:
from torch.autograd import Variable

var = Variable(torch.ones(3), requires_grad = True)
var

tensor([1., 1., 1.], requires_grad=True)