# Workshop Redes Neurais
## Grupo Turing

### Proposta de roteiro para o nb (deletar depois)

#### O que deve ser falado antes do nb?
- Introdução à redes neurais
- estrutura geral de uma rede neural (talvez falar que é parecido com uma regressão logística?)
- computation graph (talvez?)
- forward propagation
- back propagation (se falar de fp acho que é a sequência lógica)
- otimizaçaõ e gradient descent

#### Conteúdos do nb
- Básico de Pytorch
  - comparação com np
  - operações básicas
  - Variables (falar de back propagation?)
- Implementando uma NN
  - Implementar uma regressão logística (?)
  - Implementar NN
  - Falar sobre CNN e LSTM (?)
  

### Básicos de Pytorch

Primeiro vamos ver alguns análogos entre **numpy** e **Pytorch**

#### Matrizes
 - Em Pytorch, matrizes (*arrays*) são chamados de tensores.
 - Uma matriz $3\times3$, por exemplo é um tensor $3\times3$
 - Podemos criar um array numpy com o método `np.numpy()`
 - Podemos pegar o tipo do array com `type()`
 - Podemos pegar o formato do *array* com `np.shape()`. Linha $\times$ Coluna

In [15]:
import numpy as np
import math

array = [[1,2,3],[4,5,6]]
primeiro_array = np.array(array) # array 2x3
print(f"Array do tipo: {type(primeiro_array)}")
print(f"Array de formato: {np.shape(primeiro_array)}")
print(primeiro_array)

Array do tipo: <class 'numpy.ndarray'>
Array de formato: (2, 3)
[[1 2 3]
 [4 5 6]]


- Criamos um tensor com o método `torch.tensor()`
- `tensor.type`: tipo do *array*, nesse caso um tensor
- `tensor.shape`: formato do *array*. Linha $\times$ Coluna 

In [2]:
import torch

tensor = torch.Tensor(array)
print(f"Array do tipo: {tensor.type}")
print(f"Array de formato: {tensor.shape}")
print(tensor)

Array do tipo: <built-in method type of Tensor object at 0x7f0179470c80>
Array de formato: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


Podemos fazer a alocação de *arrays* de maneira análoga nas duas linguages:
 - `np.ones()` = `torch.ones()`
 - `np.random.rand()` = `torch.rand()`

In [3]:
print(f"Numpy:\n {np.ones((2,3))}\n")

print(torch.ones((2,3)))

Numpy:
 [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [4]:
print(f"Numpy:\n {np.random.rand(2,3)}\n")

print(torch.rand(2,3))

Numpy:
 [[0.63693605 0.22879151 0.9534643 ]
 [0.77120718 0.7379526  0.23432412]]

tensor([[0.9186, 0.2801, 0.6309],
        [0.9765, 0.9425, 0.5911]])


Em muitos pontos **numpy** e **pytorch** são bem parecidos em suas estruturas, e muitas das vezes podemos utilizar os dois em conjunto. Assim normalmente convertemos resultados de redes neurais - que são tensores - para **arrays** de **numpy**.

Os métodos para fazer a conversão entre tensores e arrays numpy:
 - `torch.from_numpy()`: de um array numpy para um tensore
 - `numpy()`: de um tensor para um array numpy

In [5]:
array = np.random.rand(2,2)
print(f"{type(array)} \n {array} \n")

de_numpy_para_tensor = torch.from_numpy(array)
print(f"{de_numpy_para_tensor} \n")

tensor = de_numpy_para_tensor
de_tensor_para_numpy = tensor.numpy()
print(f"{type(de_tensor_para_numpy)} \n {de_tensor_para_numpy}")

<class 'numpy.ndarray'> 
 [[0.40047898 0.55357586]
 [0.52405586 0.34592202]] 

tensor([[0.4005, 0.5536],
        [0.5241, 0.3459]], dtype=torch.float64) 

<class 'numpy.ndarray'> 
 [[0.40047898 0.55357586]
 [0.52405586 0.34592202]]


### Matemática básica com Pytorch
*considere a e b dois tensores*

- Redefinir o tamanho: `view()`
- Adição: `torch.add(a,b)` = a + b
- Subtração: `a.sub(b)` = a - b
- Multiplicação elemento-a-elemento = `torch.mul(a,b)` = a * b
- Divisão elemento-a-elemento = torch.div(a,b) = a / b
- Média: a.mean()
- Desvio Padrão (Standart Deviantion - std): a.std()

In [6]:
tensor = torch.ones(3,3)
print("\n", tensor, "\n")

print(f"{tensor.view(9).shape}: {tensor.view(9)} \n")

print(f"Adição: \n{torch.add(tensor, tensor)} \n")

print(f"Subtração: \n{torch.sub(tensor, tensor)} \n")

print(f"Multiplicação elemento-a-elemento: \n{torch.mul(tensor, tensor)} \n")

print(f"Divisão elemento-a-elemento: \n{torch.div(tensor, tensor)} \n")

tensor = torch.Tensor([1,2,3,4,5])
print(f"Média: {tensor.mean()} \n")

print(f"Desvio padrão: {tensor.std()} \n")


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

torch.Size([9]): tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.]) 

Adição: 
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) 

Subtração: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

Multiplicação elemento-a-elemento: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Divisão elemento-a-elemento: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

Média: 3.0 

Desvio padrão: 1.5811388492584229 



# ATENÇÃO COLOCAR/FAZER EXPLICAÇÃO DE BACKPROP AQUI

### Variáveis

- Acumulam os gradientes
- Na rede neural utilizaremos pytorch. Como explicamos nas redes neurais os gradientes são calculados na *backpropagation*.
- A diferença entre variáveis e tensores é a de que variáveis acumulam os gradientes
- Também podemos fazer operações matemáticas com variáveis
- Dessa maneira, se queremos fazer a *backpropagation* precisamos de variáveis

In [7]:
from torch.autograd import Variable

var = Variable(torch.ones(3), requires_grad = True)
var

tensor([1., 1., 1.], requires_grad=True)

Vamos ver um exemplo de como as Variávies são utilizadas em uma *backpropagation*, com duas função $f(y) = \sum y$, $y(x) = x^2$ e $x = (3,5)$

In [38]:
array = [3,5]
tensor = torch.Tensor(array)
x = Variable(tensor, requires_grad = True)
y = x**2
print(f" x = {x}")

f = sum(y)
print(f" f =  {f}")

f.backward()

print(f"Gradientes: {x.grad}")

 x = tensor([3., 5.], requires_grad=True)
 f =  34.0
Gradientes: tensor([ 6., 10.])


Vamos explicar passo a passo quais foram as operações feitas pelo Pytorch:
- Primeiro ele recebe os elementos do tensor e faz a primeira operação com eles $y_1 = 3^2 = 9$ e $y_2 = 5^2 = 25$
- Agora ele soma o tensor, retornando assim um único valor escalar: $\sum_i y_i = y_1 + y_2 = 9 + 25 = 34$
- O gradiente é a derivada parcial de cada elemento, ou seja o gradiente "1" é a derivada relativa à $y_1$ e o gradiente "2" é relativo à $y_2$ 
- derivada relativa à $y_1$ é $\frac{\partial}{\partial y_1}(3^2) = 2*3 = 6$
- derivada relativa à $y_2$ é $\frac{\partial}{\partial y_2}(5^2) = 2*5 = 10$
- Assim ficamos com os gradientes $(6, 10)$